cities:
  nyc:
    name: "New York City"
    state_fips: "36"
    counties: ["061","047","081","005","085"]
    bbox:
      west: -74.25
      south: 40.50
      east: -73.70
      north: 40.92
    geofabrik: "north-america/us/new-york"

  chicago:
    name: "Chicago"
    state_fips: "17"
    counties: ["031"]
    bbox:
      west: -87.94
      south: 41.64
      east: -87.52
      north: 42.02
    geofabrik: "north-america/us/illinois"

  sf:
    name: "San Francisco"
    state_fips: "06"
    counties: ["075"]
    bbox:
      west: -122.52
      south: 37.71
      east: -122.35
      north: 37.81
    geofabrik: "north-america/us/california"
